apiVersion: apps/v1
kind: Deployment
metadata:
  name: listapro-backend
  namespace: listapro
  labels:
    app: listapro-backend
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: listapro-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: listapro-backend
        environment: production
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - name: backend
          image: "brunovn7/listapro-backend:latest"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 2
            successThreshold: 1
          envFrom:
            - configMapRef:
                name: backend-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASSWORD
