name: Deploy Infraestrutura

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do codigo
      uses: actions/checkout@v2

    - name: Instalar terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.2

    - name: Inicializar Terraform
      run: terraform init

    - name: Validar codigo
      run: terraform validate

    - name: Aplicar Infraestrutura
      run: terraform apply -auto-approve
      env:
        TF_VAR_do_token: ${{ secrets.DO_TOKEN }}