version: '3'

services:
  nextjs:
    image: brunovn7/listapro-frontend:latest
    container_name: listapro-frontend
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${BACKEND_URL}