version: '3'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: nextjs-app
    environment:
      - NEXT_PUBLIC_API_URL=${BACKEND_URL}
    
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nextjs
    restart: always
    container_name: nginx