apiVersion: v1
kind: Service
metadata:
  name: listapro-frontend-service
  namespace: listapro
  labels:
    app: listapro-frontend
    environment: production
spec:
  type: LoadBalancer
  selector:
    app: listapro-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
