apiVersion: apps/v1
kind: Deployment
metadata:
  name: listapro-backend-stage
  namespace: listapro-stage
  labels:
    app: listapro-backend-stage
    environment: stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listapro-backend-stage
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: listapro-backend-stage
        environment: stage
    spec:
      containers:
        - name: backend
          image: "brunovn7/listapro-backend:latest"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 35
            periodSeconds: 20
          envFrom:
            - configMapRef:
                name: backend-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASSWORD