apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: stage
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend 
  template:
    metadata:
      labels:
        app: backend  
    spec:
      containers:
        - name: backend
          image: "brunovn7/listapro-backend:dev"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 35
            periodSeconds: 20
          envFrom:
            - configMapRef:
                name: backend-config