apiVersion: v1
kind: Service
metadata:
  name: listapro-backend-stage-service
  namespace: listapro-stage
  labels:
    app: listapro-backend-stage
spec:
  type: ClusterIP
  selector:
    app: listapro-backend-stage
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080