apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: production
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql