apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: listapro-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "postgres:17"  
          imagePullPolicy: Always
          resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
              limits:
                cpu: "512m"
                memory: "512Mi"
          ports:
            - containerPort: 5432
          envFrom:  
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim