apiVersion: v1
kind: Service
metadata:
  name: listapro-frontend-stage-service
  namespace: listapro-stage
  labels:
    app: listapro-frontend-stage
    environment: stage
spec:
  type: LoadBalancer
  selector:
    app: listapro-frontend-stage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http