apiVersion: apps/v1
kind: Deployment
metadata:
  name: listapro-frontend-stage
  namespace: listapro-stage
  labels:
    app: listapro-frontend-stage
    environment: stage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: listapro-frontend-stage
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: listapro-frontend-stage
        environment: stage
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/api/metrics"
    spec:
      containers:
        - name: listapro-frontend
          image: brunovn7/listapro-frontend:stage
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: ENVIRONMENT
              value: "stage"
            - name: NODE_ENV
              value: "staging"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: listapro-stage-secret
                  key: database-url
          envFrom:
            - configMapRef:
                name: frontend-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10