version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: listapro
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: senha
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    image: brunovn7/listapro-backend:latest
    container_name: backend
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_NAME: listapro
      DB_USER: backend
      DB_PASSWORD: senha
      DB_PORT: "5432"
      DB_SSLMODE: disable
    ports:
      - "8080:8080"

  frontend:
    image: brunovn7/listapro-frontend:latest
    container_name: frontend
    depends_on:
      - backend
    environment:
      BACKEND_URL: http://backend:8080
    ports:
      - "3000:80"

volumes:
  postgres_data:
