apiVersion: v1
kind: Service
metadata:
  name: listapro-frontend-prod-service
  namespace: listapro-prod
  labels:
    app: listapro-frontend-prod
    environment: production
spec:
  type: LoadBalancer
  selector:
    app: listapro-frontend-prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http