apiVersion: apps/v1
kind: Deployment
metadata:
  name: listapro-frontend-prod
  namespace: listapro-prod
  labels:
    app: listapro-frontend-prod
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: listapro-frontend-prod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: listapro-frontend-prod
        environment: production
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/api/metrics"
    spec:
      containers:
        - name: listapro-frontend
          image: brunovn7/listapro-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          env:
            - name: ENVIRONMENT
              value: "production"
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: listapro-prod-secret
                  key: database-url
          envFrom:
            - configMapRef:
                name: frontend-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10