apiVersion: v1
kind: Service
metadata:
  name: nextjs-frontend
  namespace: production
spec:
  type: LoadBalancer
  selector:
    app: nextjs-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80