apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: listapro-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "postgres:17"  
          imagePullPolicy: IfNotPresent
          resources:
              requests:
                cpu: "50m"
                memory: "128Mi"
              limits:
                cpu: "250m"
                memory: "256Mi"
          ports:
            - containerPort: 5432
          envFrom:  
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim